import assert from 'node:assert/strict';
import {eventMapper} from './opencode.js';
import {makeHooks} from './cline.js';
const rows=[],report=(...args)=>rows.push(args), last=()=>rows.at(-1)[1];
const oc=eventMapper(report),event=(type,p={})=>oc({event:{type,properties:{sessionID:'oc',...p}}});
event('session.status',{status:{type:'busy'}});assert.equal(last(),'working');
event('permission.v2.asked',{id:'a'});event('question.asked',{id:'b'});
event('permission.v2.replied',{requestID:'a'});assert.equal(last(),'needs_input');
event('session.status',{status:{type:'busy'}});assert.equal(last(),'needs_input');
event('question.replied',{requestID:'b'});assert.equal(last(),'working');
event('session.error',{error:{name:'APIError'}});event('session.idle');assert.equal(last(),'error');
event('session.status',{status:{type:'busy'}});event('session.idle');assert.equal(last(),'completed');
event('session.deleted');assert.equal(last(),'ended');
const cl=makeHooks(report,'cl',15), snapshot={agentId:'a'},toolCall={toolCallId:'tool1',toolName:'read_file'};
cl.beforeRun({snapshot});assert.equal(last(),'working');
cl.beforeTool({snapshot,toolCall});cl.onEvent({type:'tool-started',snapshot,toolCall});
await new Promise(r=>setTimeout(r,25));assert.equal(last(),'working');
cl.beforeTool({snapshot,toolCall});await new Promise(r=>setTimeout(r,25));assert.equal(last(),'needs_input');
cl.onEvent({type:'tool-started',snapshot,toolCall});assert.equal(last(),'working');
cl.onEvent({type:'tool-started',snapshot,toolCall:{...toolCall,toolName:'ask_followup_question'}});assert.equal(last(),'needs_input');
cl.onEvent({type:'tool-finished',snapshot,toolCall});assert.equal(last(),'working');
cl.afterRun({snapshot,result:{status:'completed'}});assert.equal(last(),'completed');
cl.afterRun({snapshot,result:{status:'aborted'}});assert.equal(last(),'idle');
cl.afterRun({snapshot,result:{status:'failed'}});assert.equal(last(),'error');
console.log('OpenCode and Cline lifecycle, approval, error, cancel, and question mappings passed.');
